config/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('social/', include('social.urls', namespace='social')),
    path('transactions/', include('transactions.urls', namespace='transactions')),
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
]

social/urls.py
from django.urls import path, reverse

from rest_framework.routers import DefaultRouter

from social.apps import SocialConfig
from social.views import index, ContentListView, \
    ContentCreateView, ContentDetailView, MyContentListView, ContentUpdateView, SmartContentListView, CommentCreateView

app_name = SocialConfig.name

urlpatterns = [path('main/', index, name='main'),
               # path('content_simple_list/', CustomListView.as_view(), name='content_simple_list'),
               path('content_simple_list/', ContentListView.as_view(), name='content_simple_list'),
               path('content_my_list/', MyContentListView.as_view(), name='my_content_list'),
               path('content_smart_list/', SmartContentListView.as_view(), name='content_smart_list'),

               path('comment_create/', CommentCreateView.as_view(), name='comment_create'),
               # TODO сделать ссылки на всех шаблонах

               path('content_create/', ContentCreateView.as_view(), name='content_create'),
               path('content_update/<int:pk>/', ContentUpdateView.as_view(), name='content_update'),
               path('content_detail/<int:pk>/', ContentDetailView.as_view(), name='content_detail')

               ]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from rest_framework_simplejwt.views import TokenRefreshView

from users.apps import UsersConfig
from users.views import RegisterView, UserUpdateView, ProfileDetailView, SubscriptionsCreateView

app_name = UsersConfig.name

urlpatterns = [
    path('reg/', RegisterView.as_view(), name='reg'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile'),
    path('profile_update/<int:pk>/', UserUpdateView.as_view(), name='profile_update'),
    path('subscribe/', SubscriptionsCreateView.as_view(), name='subscribe'),

]

social/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


# Create your models here.


class Content(models.Model):
    name = models.CharField(max_length=120, verbose_name="Название поста")
    text = models.TextField(verbose_name="Текст поста", **NULLABLE)
    date = models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления")
    image = models.ImageField(upload_to="social/", verbose_name="Изображение", **NULLABLE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор", related_name="content_author")
    subscribers_only = models.BooleanField(default=False, verbose_name="Только для подписчиков")

    # добавить поле для требуемого уровня подписки
    def get_like_count(self):
        return self.like_set.count()

    like_count = property(get_like_count)

    def get_comment_count(self):
        return self.comment_content.count()

    comment_count = property(get_comment_count)

    def __str__(self):
        return f'Пост про {self.name}'

    class Meta:
        ordering = ['-date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Like(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE, verbose_name="Лайк")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь", related_name='like_author')


class Comment(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE, verbose_name="Комментарий",
                                related_name='comment_content')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор", related_name='comment_author')
    text = models.TextField(verbose_name="Текст комментария")
    date = models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления")
    is_paid = models.BooleanField(default=False, verbose_name="Платный комментарий")

    # cost = models.IntegerField(**NULLABLE, verbose_name="Стоимость") нужно сделать привязку к модели транзакция

    def __str__(self):
        return f'Комментарий к {self.content}'

    class Meta:
        ordering = ['-date']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models

NULLABLE = {'blank': True, 'null': True}
phone_regex = RegexValidator(regex=r'^\+?\d{9,15}$', message='Телефон должен содержать от 9 до 15 цифр')


class User(AbstractUser):
    username = None
    # Регистрация по номеру телефона
    telephone = models.CharField(max_length=20, validators=[phone_regex], verbose_name='Телефон', unique=True)
    first_name = models.CharField(max_length=20, verbose_name='Имя')
    last_name = models.CharField(max_length=20, verbose_name='Фамилия')
    email = models.EmailField(verbose_name='Email', unique=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True, verbose_name='Аватар')
    description = models.CharField(max_length=20, verbose_name='О себе')
    wallet = models.IntegerField(default=0, verbose_name='Баланс')
    USERNAME_FIELD = "telephone"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.first_name}, {self.email}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Subscription(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='На кого подписан',
                               related_name='subscribed_to')
    proprietor = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Подписчик', related_name='subscriber')


# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from users.models import User, Subscription


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('telephone', 'password1', 'password2',)


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('telephone', 'first_name', 'last_name', 'email', 'description')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class SubscriptionForm(forms.ModelForm):

    class Meta:
        model = Subscription
        fields = '__all__'

users/views.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, DetailView, ListView
from rest_framework import generics, request
from rest_framework.generics import get_object_or_404
from rest_framework.response import Response
from rest_framework.views import APIView

from social.models import Content
from transactions.models import Transaction
from users.forms import UserRegisterForm, UserProfileForm, SubscriptionForm
from users.models import User, Subscription
from rest_framework.permissions import AllowAny, IsAuthenticated

from users.permission import IsTrueUser
from users.serializers import UserSerializer, MyTokenObtainPairSerializer

from rest_framework_simplejwt.views import TokenObtainPairView


# Create your views here.


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('social:main')


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users/profile.html'
    context_object_name = 'author'
    success_url = reverse_lazy('users:profile')
    form_class = SubscriptionForm

    def get_initial(self):
        # Получаем объект пользователя по pk
        proprietor = self.request.user
        author = get_object_or_404(User, pk=self.kwargs['pk'])
        # Предзаполняем данные формы
        initial_data = {
            'proprietor': proprietor,
            'author': author,
            # Добавьте другие поля, которые вы хотите предзаполнить
        }
        return initial_data

    def get_context_data(self, **kwargs):
        context = {}
        context['subscriptions'] = Subscription.objects.filter(proprietor=self.request.user)
        context['content_list'] = Content.objects.filter(author=kwargs['pk'])
        context['object'] = User.objects.get(pk=kwargs['pk'])
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        form = self.form_class(initial=self.get_initial())
        context['form'] = form
        form.fields['author'].queryset = User.objects.filter(pk=kwargs['pk'])
        form.fields['proprietor'].queryset = User.objects.filter(pk=self.request.user.pk)

        return render(request, self.template_name, context)

    def post(self, request, pk):
        form = self.form_class(request.POST)
        if form.is_valid():
            # Здесь вы можете сохранить данные в базу данных или выполнить другие действия
            print(form.cleaned_data)
            return redirect('users:profile', pk=pk)
        else:
            return render(request, self.template_name, {'form': form})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    # TODO выключить возможность редактировать кошелек, уровень автора и тд
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class SubscriptionsCreateView(LoginRequiredMixin, CreateView):
    model = Subscription
    form_class = SubscriptionForm
    template_name = 'users/subscription_form.html'
    success_url = reverse_lazy('social:main')


"""
--------------------------------------------------------------------------------------------------
"""

# class UserCreateAPIView(generics.CreateAPIView):
#     """
#     Создание пользователя
#     """
#     permission_classes = [AllowAny]
#     serializer_class = UserSerializer
#
#
# class UserRetrieveAPIView(generics.RetrieveAPIView):
#     permission_classes = [IsTrueUser, IsAuthenticated]
#     serializer_class = UserSerializer
#     queryset = User.objects.all()
#
#
# class UserUpdateAPIView(generics.UpdateAPIView):
#     permission_classes = [IsTrueUser, IsAuthenticated]
#     serializer_class = UserSerializer
#     queryset = User.objects.all()
#
#
# class UserDestroyAPIView(generics.DestroyAPIView):
#     permission_classes = [IsTrueUser, IsAuthenticated]
#     queryset = User.objects.all()
#
#
# class UserCheckLevelAPIView(APIView):
#     permission_classes = [IsTrueUser, IsAuthenticated]
#
#     def get(self, request, *args, **kwargs):  # TODO надо ли переносить этот метод в сериализатор?
#         user = self.request.user
#         count = Subscription.objects.filter(author=user).count()
#         if count >= 10:
#             user.author_level = 1
#         elif count >= 50:
#             user.author_level = 2
#         elif count >= 100:
#             user.author_level = 3
#         user.save()
#         return Response({"message": f"Ваш уровень как автора {user.author_level}"})
#
#
# class MyTokenObtainPairView(TokenObtainPairView):
#     serializer_class = MyTokenObtainPairSerializer
#
#
# class UpdateTelegramChatIdAPIView(APIView):
#     def post(self, *args, **kwargs):
#         user = self.request.user
#         chat_id = self.request.data.get('chat_id')
#         user.chat_id = chat_id
#         user.save()
#
#         return Response({'message': f'Чат {chat_id} в телеграмме успешно привязан'})
#
#
# class SubscriptionAPIView(APIView):
#     def post(self, *args, **kwargs):
#         user = self.request.user
#         author = User.objects.get(pk=self.request.data.get('author'))
#         level = self.request.data.get('level')
#         print(user, author, level)
#         if Subscription.objects.filter(proprietor=user.id, author=author.id, level=level).exists():
#             print('exists')
#             return Response({'message': 'Вы уже подписаны на этого автора'})
#         user.wallet -= 100 * level  # TODO сделать проверку кошелька
#         subscription = Subscription(author=author, level=level, proprietor=user).save()
#         return Response({'message': f'Вы получили подписку {level} уровня на {author.name}'})

users/templates/users/login.html
{% extends 'social/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
{% if user.is_authenticated%}
<div class="col">
    <div class="card">
        <div class="card-text">
            Вы уже аутентифицированы как {{user.name}}
        </div>
    </div>
</div>
{% else %}
<div class="col">
    <div class="card">
        <div class="card-body-fluid">
            <form method="post">
                <h1>Вход</h1>
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-secondary">Подтвердить</button>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

users/templates/users/profile.html
{% extends 'social/base.html' %}
{% load static %}
{% load my_filters %}
{% load crispy_forms_tags %}


{% block content %}
{% for content in content_list %}

<div class="card">
    <img src="{{ content.images|mymedia }}" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{ content.name }}</h5>
        <p class="card-text">{{ content.text }}</p>
        <h6>{{ content.date }}</h6>
        <a href="{% url 'social:content_detail' content.pk %}" class="btn btn-primary">К подробностям</a>
        <hr>
        <a class="btn btn-primary" href="{% url 'social:comment_create' %}" role="button">Написать комментарий</a>

        <a class="btn btn-primary" data-bs-toggle="collapse" href="#{{ content.id }}" role="button"
           aria-expanded="false"
           aria-controls="{{ content.id }}">
            Комменты
        </a>
        {% if content.author.id != user.id %}
        <a class="btn btn-primary" href="{% url 'users:profile'  content.author.id %}" role="button">Профиль автора</a>
        {% endif %}


        <hr>
    </div>
</div>


{% endfor %}
{% endblock %}


{% block text %}

<div class="card">
    <img src="..." class="card-img-top w-auto p-3" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{ author.first_name}}</h5>
        <p class="card-text"> {{ author.description }}</p>

        {% if author.id == user.id %}
        <p class="card-text"> Уровень как автора - {{ author.author_level }} </p>
        <p class="card-text"> Баланс кошелька - {{ author.wallet }} </p>
        <a href="{% url 'users:profile_update' user.pk %}" class="btn btn-primary">Редактировать</a>

        {% else %}
        <a class="btn btn-primary" href="{% url 'users:subscribe' %}" role="button">Подписаться</a>
        {% endif %}
    </div>
</div>

<div class="card">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit">Сохранить изменения</button>
    </form>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'social/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
{% if user.is_authenticated %}
<h1>Вы уже были зарегистрированы </h1>
{% else %}
<div class="col">
    <div class="card">
        <div class="card-body-fluid">
            <form method="post">
                <h1>Регистрация</h1>
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-secondary">Подтвердить</button>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

users/templates/users/subscription_form.html
{% extends 'social/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<div class="col">
    <div class="card">
        <div class="card-body-fluid">
            <form method="post">
                <h1>Профиль</h1>
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-secondary">Подтвердить</button>
            </form>

        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'social/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<div class="col">
    <div class="card">
        <div class="card-body-fluid">
            <form method="post">
                <h1>Профиль</h1>
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-secondary">Подтвердить</button>
            </form>

        </div>
    </div>
</div>
{% endblock %}