config/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('social/', include('social.urls', namespace='social')),
    path('transactions/', include('transactions.urls', namespace='transactions')),
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
]

social/urls.py
from django.urls import path, reverse

from rest_framework.routers import DefaultRouter

from social.apps import SocialConfig
from social.views import index, ContentListView, \
    ContentCreateView, ContentDetailView, MyContentListView, ContentUpdateView, SmartContentListView, CommentCreateView

app_name = SocialConfig.name

urlpatterns = [path('main/', index, name='main'),
               # path('content_simple_list/', CustomListView.as_view(), name='content_simple_list'),
               path('content_simple_list/', ContentListView.as_view(), name='content_simple_list'),
               path('content_my_list/', MyContentListView.as_view(), name='my_content_list'),
               path('content_smart_list/', SmartContentListView.as_view(), name='content_smart_list'),

               path('comment_create/', CommentCreateView.as_view(), name='comment_create'),
               # TODO сделать ссылки на всех шаблонах

               path('content_create/', ContentCreateView.as_view(), name='content_create'),
               path('content_update/<int:pk>/', ContentUpdateView.as_view(), name='content_update'),
               path('content_detail/<int:pk>/', ContentDetailView.as_view(), name='content_detail')

               ]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from rest_framework_simplejwt.views import TokenRefreshView

from users.apps import UsersConfig
from users.views import RegisterView, UserUpdateView, ProfileDetailView, SubscriptionsCreateView

app_name = UsersConfig.name

urlpatterns = [
    path('reg/', RegisterView.as_view(), name='reg'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile'),
    path('profile_update/<int:pk>/', UserUpdateView.as_view(), name='profile_update'),
    path('subscribe/', SubscriptionsCreateView.as_view(), name='subscribe'),

]

social/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


# Create your models here.


class Content(models.Model):
    name = models.CharField(max_length=120, verbose_name="Название поста")
    text = models.TextField(verbose_name="Текст поста", **NULLABLE)
    date = models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления")
    image = models.ImageField(upload_to="social/", verbose_name="Изображение", **NULLABLE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор", related_name="content_author")
    subscribers_only = models.BooleanField(default=False, verbose_name="Только для подписчиков")

    # добавить поле для требуемого уровня подписки
    def get_like_count(self):
        return self.like_set.count()

    like_count = property(get_like_count)

    def get_comment_count(self):
        return self.comment_content.count()

    comment_count = property(get_comment_count)

    def __str__(self):
        return f'Пост про {self.name}'

    class Meta:
        ordering = ['-date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Like(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE, verbose_name="Лайк")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь", related_name='like_author')


class Comment(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE, verbose_name="Комментарий",
                                related_name='comment_content')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор", related_name='comment_author')
    text = models.TextField(verbose_name="Текст комментария")
    date = models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления")
    is_paid = models.BooleanField(default=False, verbose_name="Платный комментарий")

    # cost = models.IntegerField(**NULLABLE, verbose_name="Стоимость") нужно сделать привязку к модели транзакция

    def __str__(self):
        return f'Комментарий к {self.content}'

    class Meta:
        ordering = ['-date']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

social/forms.py
from django import forms

from social.models import Content, Comment


class ContentForm(forms.ModelForm):
    """"
    TODO Добавить проверку на уровень подписки можно тут?
    """
    class Meta:
        model = Content
        exclude = ('author',)


class CommentForm(forms.ModelForm):
    """комменты не работают, так как для создания нужно в кнопке передавать id поста к которому присоеденяется комментарий"""

    class Meta:
        model = Comment
        fields = ('author',)

social/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from django.views.generic.base import TemplateResponseMixin, View
from django.views.generic.list import MultipleObjectMixin
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework import viewsets, generics
from rest_framework.response import Response
from rest_framework.views import APIView

from social.forms import ContentForm, CommentForm
from social.models import Content, Like, Comment
from social.permissions import IsProprietor
from social.serializers import ContentSerializer, CommentsSerializer, SimpleContentSerializer
from rest_framework.status import HTTP_200_OK, HTTP_201_CREATED, HTTP_204_NO_CONTENT, HTTP_404_NOT_FOUND
from rest_framework.renderers import TemplateHTMLRenderer

from users.models import Subscription
from users.permission import IsModerator


# Create your views here.

def index(request):
    """"
    пустая главная страница на которой будет логотип и приветственная инфа + конпки ведущие на регистрацию и тестовую ленту
    """
    return render(request, 'social/index.html')


class ContentListView(LoginRequiredMixin, ListView):
    """
    Лента выдающая контент авторов на которых подписан пользователь
    TODO сделать фильтровку по уровню подписки/контента
    """
    model = Content
    template_name = 'social/content_list.html'
    context_object_name = 'content_list'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        comments_list = Comment.objects.all()
        context['comments_list'] = comments_list
        likes_list = Like.objects.filter(author=self.request.user)
        context['likes_list'] = likes_list
        return context

    def get_queryset(self):
        user = self.request.user
        subscribe = Subscription.objects.filter(proprietor=user).values_list('author', flat=True)
        print(subscribe)
        queryset = Content.objects.filter(Q(author__in=subscribe))
        return queryset


class SmartContentListView(ContentListView):


    def get_queryset(self):
        user = self.request.user
        subscribe = Subscription.objects.filter(proprietor=user).values_list('author', flat=True)
        queryset = Content.objects.exclude(author__in=subscribe)
        return queryset


class MyContentListView(LoginRequiredMixin, ListView):  # TODO наследуйтесь от ContentListView
    """
    Лента своих постов
    """

    model = Content
    template_name = 'social/content_my_list.html'
    context_object_name = 'content_list'

    def get_queryset(self):
        queryset = Content.objects.filter(author=self.request.user)
        return queryset


class ContentCreateView(LoginRequiredMixin, CreateView):
    """
    Создание контента,
    Нужно добавить проверку на уровень автора, чтобы он мог создавать посты не выше своего уровня
    """
    model = Content
    form_class = ContentForm
    success_url = reverse_lazy('social:content_simple_list')  # TODO не забыть отключить поле владельца

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ContentDetailView(LoginRequiredMixin, DetailView):
    """
    Детальный просмотр постов, тут же есть кнопка подписаться на автора,
    TODO в идеале сделать так чтобы подписаться можно было без перехода на отдельную страницу
    """
    model = Content
    context_object_name = 'content'
    template_name = 'social/content_detail.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        comments_list = Comment.objects.all()  # TODO сделать фильтрацию
        context['comments_list'] = comments_list
        return context


class ContentUpdateView(LoginRequiredMixin, UpdateView):
    model = Content
    form_class = ContentForm
    success_url = reverse_lazy('social:my_content_list')

    def form_valid(self, form):
        self.object = form.save()
        if self.request.user != self.object.author:
            reverse_lazy('social:content_simple_list')
            print('это не твой продукт брысь')
            form.add_error(None, 'это не твой продукт брысь')
            return super().form_invalid(form)
        self.object.save()
        return super().form_valid(form)


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    success_url = reverse_lazy('social:content_simple_list')  # TODO доделать CRUD
    template_name = 'social/comments/comment_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)



"""
----------------------------------------------------------------------------------------------------------
"""
# class ContentViewSet(viewsets.ModelViewSet):
#
#     queryset = Content.objects.all()
#     serializer_class = ContentSerializer
#
#     def get_permissions(self):
#         if self.action == 'create':
#             self.permission_classes = [IsAuthenticated]
#         elif self.action == 'list':
#             self.renderer_classes = [TemplateHTMLRenderer]
#             self.template_name = 'social/content_list.html'
#             # self.serializer_class = SimpleContentSerializer
#             self.permission_classes = [AllowAny]
#         elif self.action == 'retrieve':
#             self.permission_classes = [IsAuthenticated]
#         elif self.action == 'update':
#             self.permission_classes = [IsAuthenticated, IsProprietor]
#         elif self.action == 'partial_update':
#             self.permission_classes = [IsAuthenticated, IsProprietor]
#         elif self.action == 'destroy':
#             self.permission_classes = [IsAuthenticated, IsProprietor]
#         return [permission() for permission in self.permission_classes]
#
#     def perform_create(self, serializer):
#         serializer.save(author=self.request.user)
#
#     # def get(self):
#     #     return Response({"content_list": Content.objects.all()})
#
#     def get(self, request):
#
#         content_list = Content.objects.all()
#         context = {'content_list': content_list}
#         return Response(context)
#
#     def get_queryset(self):
#         queryset = Content.objects.all()
#         content_filter = self.request.query_params.get('selection')
#         print(content_filter)
#         if self.action == 'list':
#             if content_filter:
#                 ids_str = ','.join([str(id) for id in content_filter])
#
#                 # Создание queryset из записей, ID которых есть в списке
#                 queryset = Content.objects.filter(
#                     author__id__in=ids_str.split(','))  # позволяет получить посты только с определенными авторами
#                 # queryset = queryset.filter(Q(pk__in=ids_str.split(',')))  # NOTE разобраться позже
#             # else:
#             #     queryset = queryset.filter(level__lte=self.request.user.level)
#
#         return queryset
#
#
# class LakeAPIView(APIView):
#     def post(self, *args, **kwargs):
#         content_id = self.request.data.get('content_id')
#         user = self.request.user
#         try:
#             content = Content.objects.get(id=content_id)
#         except Content.DoesNotExist:
#             message = f'Такого поста не существует'
#             code = HTTP_404_NOT_FOUND
#         else:
#             if Like.objects.filter(author=user, content=content).exists():
#                 Like.objects.filter(author=user, content=content).delete()
#                 message = 'Удалено'
#                 code = HTTP_204_NO_CONTENT
#             else:
#                 Like.objects.create(author=user, content=content).save()
#                 message = 'Добавлено'
#                 code = HTTP_201_CREATED
#
#         return Response({'message': message}, status=code)
#
#
# class CommentViewSet(viewsets.ModelViewSet):
#     queryset = Comment.objects.all()
#     serializer_class = CommentsSerializer
#
#     def get_queryset(self):
#         queryset = Comment.objects.all()
#         content_filter = self.request.query_params.get('content_filter')
#         if content_filter:
#             queryset = queryset.filter(content_id=content_filter)
#         return queryset
#
#     def get_permissions(self):
#         if self.action == 'create':
#             self.permission_classes = [IsAuthenticated]
#         elif self.action == 'list':
#             self.permission_classes = [IsAuthenticated]
#         elif self.action == 'retrieve':
#             self.permission_classes = [IsAuthenticated]
#         elif self.action == 'update':
#             self.permission_classes = [IsAuthenticated, IsProprietor]
#         elif self.action == 'partial_update':
#             self.permission_classes = [IsAuthenticated, IsProprietor]
#         elif self.action == 'destroy':
#             self.permission_classes = [IsAuthenticated, IsProprietor]
#         return [permission() for permission in self.permission_classes]
#
#     def perform_create(self, serializer):
#         serializer.save(author=self.request.user)

social/templates/social/content_detail.html
{% extends 'social/base.html' %}
{% load static %}

{% block content %}
<div class="card">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{ object.name }}</h5>
        <p class="card-text">{{ content.text }}</p>
        <h6>{{ content.date }}</h6>

        <hr>

        {% for comment in comments_list %}
        {% if content.id == comment.content.id %}

        <p class="card-text">
            {{comment.text}} -
            {{comment.author.name}}
        </p>


        {% endif %}
        {% endfor %}
        <hr>
    </div>
</div>


{% endblock %}


{% block text %}


<p> Тут будет чат комменты и тд </p>
{% endblock %}

social/templates/social/content_form.html
{% extends 'social/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<div class="col">
    <div class="card">
        <div class="card-body-fluid">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-secondary">Подтвердить</button>
            </form>

        </div>
    </div>
</div>
{% endblock %}

social/templates/social/content_list.html
{% extends 'social/base.html' %}
{% load static %}
{% load my_filters %}


{% block content %}
{% for content in content_list %}

<div class="card">
    <img src="{{ content.images|mymedia }}" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{ content.name }}</h5>
        <p class="card-text">{{ content.text }}</p>
        <h6>{{ content.date }}</h6>
        <a href="{% url 'social:content_detail' content.pk %}" class="btn btn-primary">К подробностям</a>
        <hr>
        <a class="btn btn-primary" href="{% url 'social:comment_create' %}" role="button">Написать комментарий</a>

        <a class="btn btn-primary" data-bs-toggle="collapse" href="#{{ content.id }}" role="button"
           aria-expanded="false"
           aria-controls="{{ content.id }}">
            Комменты
        </a>
        {% if content.author.id != user.id %}
        <a class="btn btn-primary" href="{% url 'users:profile'  content.author.id %}" role="button">Профиль автора</a>
        {% endif %}


        <hr>
    </div>
</div>


{% endfor %}
{% endblock %}


{% block text %}
<div data-bs-spy="scroll" data-bs-target="#navbar-example3" data-bs-smooth-scroll="true" class="scrollspy-example-2"
     tabindex="0">


    {% for content in content_list %}


    <div class="collapse" id="{{ content.id }}">
        {% for comment in comments_list %}
        {% if content.id == comment.content.id %}
        <div class="card">
            <div class="card card-body">
                <p class="card-text">
                    {{comment.text}}
                    {{comment.author.name}}
                </p>
            </div>

        </div>
        {% endif %}
        {% endfor %}
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#{{ content.id }}"
                aria-expanded="false" aria-controls="{{ content.id }}">
            Закрыть
        </button>
    </div>
    {% endfor %}
</div>


<p> Тут будет чат комменты и тд </p>
{% endblock %}

social/templates/social/content_my_list.html
{% extends 'social/base.html' %}
{% load static %}

{% block content %}
{% for content in content_list %}


<div class="card">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{ content.name }}</h5>
        <p class="card-text">{{ content.text }}</p>
        <h6>{{ content.date }}</h6>
        <a href="{% url 'social:content_update' content.pk %}" class="btn btn-primary">Редактировать</a>
        <input class="btn btn-primary" type="submit" value="Поле Отправить">
        <a class="btn btn-primary" href="#" role="button">Ссылка</a>

        <hr>
        <a class="btn btn-primary" data-bs-toggle="collapse" href="#{{ content.id }}" role="button"
           aria-expanded="false"
           aria-controls="{{ content.id }}">
            Комменты
        </a>


        <hr>
    </div>
</div>


{% endfor %}
{% endblock %}


{% block text %}
{% for content in content_list %}


<div class="collapse" id="{{ content.id }}">
    {% for comment in comments_list %}
    {% if content.id == comment.content.id %}
    <div class="card">
        <div class="card card-body">
            <p class="card-text">
                {{comment.text}} -
                {{comment.author.name}}
            </p>
        </div>

    </div>
    {% endif %}
    {% endfor %}
    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#{{ content.id }}"
            aria-expanded="false" aria-controls="{{ content.id }}">
        Закрыть
    </button>
</div>
{% endfor %}


<p> Тут будет чат комменты и тд </p>
{% endblock %}

social/templates/social/index.html
{% extends 'social/base.html' %}
{% load static %}

{% block content %}
<p> тут будет приветственоое сообщение</p>
{% endblock %}


{% block text %}
<p> Тут будет чат комменты и тд </p>
{% endblock %}